modLoader="javafml" #mandatory
loaderVersion="[25,)" #mandatory
credits="Thanks to the forge team for their work and occasional pointers in the right direction :)" #optional
[[mods]] #mandatory
modId="buildhelper" #mandatory
version="2.0.0.0" #mandatory
displayName="Torojima's Buildhelper" #mandatory
description='''
DESCRIPTION
'''